### ISSUE TITLE
老师这边关于编码的处理可以请教一下细节么

### ISSUE THREAD

**Issue by reckless-huang** [t924417424/ssh_manage#3]

**Comment by reckless-huang** [comment]
我也遇到了中文乱码和ws连接因为utf8编码错误断开的问题

**Comment by t924417424** [comment]
[前端处理](https://github.com/t924417424/ssh_manage/blob/4eb071c3029e188999117563d4f215179e0e625a/static/xterm/main.js#L81)
[后端使用WebsocketBinaryType发送数据包](https://github.com/t924417424/ssh_manage/blob/4eb071c3029e188999117563d4f215179e0e625a/controller/term.go#L57)


编码问题可以使用websocket的binarytype进行收发数据包，前端进行对应的转换操作即可

**Comment by reckless-huang** [comment]
前端转化这一块有点看不明白，具体是哪一块的代码呀

**Comment by reckless-huang** [comment]
我尝试加入这一段 `        let reader = new FileReader();
        reader.onload = function (event) {
          let content = reader.result;//内容就在这里
          //delete reader
          //console.log(content)
          term.write(content);
          update_path(content);
        };
        reader.readAsText(e.data);`
然后前端报错了
ContainerTerminal.vue?41cc:85 Uncaught TypeError: Failed to execute 'readAsText' on 'FileReader': parameter 1 is not of type 'Blob'.
    at WebSocket.ws.onmessage (ContainerTerminal.vue?41cc:85)

**Comment by t924417424** [comment]
你这个报错是因为你reader.readAsText的参数不是blob类型的数据，后端发送的数据包是需要指明binaryType的

**Comment by reckless-huang** [comment]
> 你这个报错是因为你reader.readAsText的参数不是blob类型的数据，后端发送的数据包是需要指明binaryType的

已经指定了binary了

**Comment by t924417424** [comment]
可以打印一下你的e.data吗

**Comment by reckless-huang** [comment]
![image](https://user-images.githubusercontent.com/53162954/141224780-2a0ef054-1ea2-4ac3-87a8-5fb781d9f868.png)

**Comment by reckless-huang** [comment]
![image](https://user-images.githubusercontent.com/53162954/141224934-ac991a88-b3c3-4921-9976-41f57359a880.png)

**Comment by t924417424** [comment]
开发者工具里面，与后端建立websocket的原数据包给我看一下

**Comment by reckless-huang** [comment]
![image](https://user-images.githubusercontent.com/53162954/141225254-1e95427c-d9f5-499f-8e8b-7b7aa5cd3213.png)

**Comment by t924417424** [comment]
打印一下onmessage接受到的参数

**Comment by reckless-huang** [comment]
![image](https://user-images.githubusercontent.com/53162954/141225760-532f1647-476e-4373-830e-98298d40119d.png)

**Comment by reckless-huang** [comment]
需要展开么

**Comment by reckless-huang** [comment]
![image](https://user-images.githubusercontent.com/53162954/141225807-390b5666-c627-4617-9fd3-19071308709f.png)

**Comment by t924417424** [comment]
你这个参数类型应该是没错的，再试试加入那段代码

**Comment by reckless-huang** [comment]
代码一直在的，现在报错不一样了
![image](https://user-images.githubusercontent.com/53162954/141226269-54839c79-6c13-4612-9d94-da67cd4ea95e.png)

**Comment by reckless-huang** [comment]
![image](https://user-images.githubusercontent.com/53162954/141226330-f7cc7f05-64cb-4e4b-8715-6a803c84c3a1.png)
我的term是保存在data的，这里好像说write方法有问题

**Comment by t924417424** [comment]
这是一个this指向性问题，尝试用一下箭头函数来修正
```
reader.onload = (event) =>  {
            let content = reader.result;//内容就在这里
            //delete reader
            //console.log(content)
            this.term.write(content);
            // update_path(content); 这段代码是我给自己的sftp功能准备的，只实现ssh的话不需要
        };
```

**Comment by t924417424** [comment]
reader.onload = (event) =>  {
            let content = reader.result;//内容就在这里
            //delete reader
            //console.log(content)
            this.term.write(content);
            // update_path(content); 这段代码是我给自己的sftp功能准备的，只实现ssh的话不需要
        };

**Comment by t924417424** [comment]
我不经常使用vue，你检查一下term在这个callback里面是否初始化

或者尝试使用箭头函数
```
reader.onload = (event) =>  {
    let content = reader.result;//内容就在这里
    //delete reader
    //console.log(content)
    this.term.write(content);
    // update_path(content); 这段代码是我给自己的sftp功能准备的，只实现ssh的话不需要
};
```

**Comment by reckless-huang** [comment]
![image](https://user-images.githubusercontent.com/53162954/141226824-e6ef6cc5-8256-41cd-bdbd-995159361f04.png)
又出现了这个

**Comment by t924417424** [comment]
注释掉这个调用就好了，这个函数是我实现sftp功能才加入的

**Comment by reckless-huang** [comment]
![image](https://user-images.githubusercontent.com/53162954/141226916-ec65eba4-5e52-4ece-9d50-5bca2b21a578.png)

**Comment by reckless-huang** [comment]
vi打开乱码   老师您是前端还是后端 都会也太强了吧

**Comment by t924417424** [comment]
[FileReader.readAsText用法详解](https://developer.mozilla.org/zh-CN/docs/Web/API/FileReader/readAsText)

FileReader.readAsText可以指定编码类型的，尝试修改一下

我主做后端，前端这块js还好，其他的不怎样

**Comment by reckless-huang** [comment]
尝试了utf8 GB2312 还是有乱码

**Comment by t924417424** [comment]
试试在后端先确定一下编码类型

**Comment by reckless-huang** [comment]
cat和more都可以正确的返回中文挺奇怪的

**Comment by t924417424** [comment]
你要确定一下是输入乱码还是输出乱码？

**Comment by reckless-huang** [comment]
输入就已经乱码了

**Comment by t924417424** [comment]
如果是输入乱码的话，就不是readAsText的问题了，而是你向服务器发送的数据包问题

**Comment by reckless-huang** [comment]
![image](https://user-images.githubusercontent.com/53162954/141228437-a8fc74aa-d062-4c50-a573-eb095f0b7fce.png)
前端log是正常的，展示不正确

**Comment by t924417424** [comment]
你的本机浏览器输入编码并不一定和你的远程主机默认编码一致

**Comment by reckless-huang** [comment]
后端收到也是正常的中文

**Comment by t924417424** [comment]
应用程序收到的是中文，但是往远程主机的term中写入的时候，那个编码你的远程主机并不一定支持

**Comment by t924417424** [comment]
可以使用`locale`命令来查看一下服务器主机编码类型

**Comment by reckless-huang** [comment]
![image](https://user-images.githubusercontent.com/53162954/141229025-81bcf4db-0c01-4e6e-b3d2-33153265174e.png)
上面是对端服务器
![image](https://user-images.githubusercontent.com/53162954/141229038-136e16fd-b72d-4d60-a573-8d36099cdff5.png)
这时我的本机ubuntu

**Comment by t924417424** [comment]
通过websocket发送给的时候服务器的时候有没有进行编码

**Comment by reckless-huang** [comment]
没有的

**Comment by reckless-huang** [comment]
![image](https://user-images.githubusercontent.com/53162954/141230686-5c2888e5-40eb-4083-a352-dd47e9aae3f2.png)
是和k8s进行交互直接实现了read

**Comment by t924417424** [comment]
[发送数据](https://github.com/t924417424/ssh_manage/blob/4eb071c3029e188999117563d4f215179e0e625a/static/xterm/main.js#L62)

试一下我的写法

**Comment by reckless-huang** [comment]
send时我也用了str2utf8这个方法的，没有效果

**Comment by t924417424** [comment]
[这是我后端写入远程的方法，你可以看看](https://github.com/t924417424/ssh_manage/blob/4eb071c3029e188999117563d4f215179e0e625a/common/core/ssh_shell_conn.go#L118)

**Comment by reckless-huang** [comment]
后端看起来是一样的直接读取内容然后转成byte切片

**Comment by t924417424** [comment]
你可以测试一下我的演示，没有这个问题

**Comment by reckless-huang** [comment]
我这边在测试一下，十分感谢老师

**Comment by reckless-huang** [comment]
搞定了中文问题了 修改家目录下的vimrc

![image](https://user-images.githubusercontent.com/53162954/141250740-aa7bdd47-82a2-4455-ab73-70c0e0d84b33.png)

**Comment by reckless-huang** [comment]
不过又出现了新问题中文输入重复 我输入一个中文 终端输入了两

**Comment by t924417424** [comment]
这个是输入法的问题，只能通过算法解决一下
